import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/provider/theme-provider'
import { ConvexClientProvider } from '@/components/provider/convex-client-provider'

const font = Open_Sans({
    variable: '--font-open-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Team Chart Application',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={cn(font.className, `antialiased`, `bg-white dark:bg-[#313333]`)}>
                <ConvexClientProvider>
                    <ThemeProvider attribute='class' defaultTheme='dark' enableSystem storageKey='discord-theme' disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </ConvexClientProvider>
            </body>
        </html>
    )
}
